### ISSUE TITLE
[$50] responsive design

### ISSUE THREAD

**Issue by cwdcwd** [cwdcwd/operation-predator#1]
### Description:
Layout of boxes needs to be responsive.

### Requirements:
- Make the data flow properly in a variety of different formats 
- targeting 
  + desktop 1024px - minimum (larger is fine)
  + tablet 768px
  + mobile 320px

### Setup & Reference:
- Live Heroku instance [here](https://tc-heatmap.herokuapp.com/)

### Submissions:
- Ensure good test coverage on all modules
- Upload documentation for how to run your submission
- Upload all your source code as a zip for review
- Winner will be required to submit a pull request with their winning code.

**Comment by cwdcwd** [comment]
@countcain I'm moving this repo to here. Are you interested in this ticket?

**Comment by countcain** [comment]
Sorry. I am busy these days.

**Comment by trevorgerring** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30055682/?type=develop&noncache=true

**Comment by countcain** [comment]
It maybe kind of hard to make it responsive! Because those canvas position are defined by number instead of css properties.

**Comment by bl0ndie** [comment]
Failed to create challenge
Status code: 503
Response body:
```
"<!DOCTYPE html>\n\t<html>\n\t  <head>\n\t\t<meta charset=\"utf-8\">\n\t\t<title>Application Error | Heroku</title>\n\t\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"https://www.herokucdn.com/favicon.ico\">\n\t\t<style media=\"screen\">\n\t\t  html,body,iframe {\n\t\t\tmargin: 0;\n\t\t\tpadding: 0;\n\t\t  }\n\t\t  html,body {\n\t\t\theight: 100%;\n\t\t\toverflow: hidden;\n\t\t  }\n\t\t  iframe {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tborder: 0;\n\t\t  }\n\t\t</style>\n\t  </head>\n\t  <body>\n\t\t<iframe src=\"//www.herokucdn.com/error-pages/application-error.html\"></iframe>\n\t  </body>\n\t</html>"
```

**Comment by bl0ndie** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30055727/?type=develop&noncache=true
